name: Backend CI

on:
  push:
    branches: [ "main", "backend" ] # Chạy khi code vào main hoặc backend
    paths:
      - 'backend/**' # Chỉ chạy khi có thay đổi trong thư mục backend
  pull_request:
    branches: [ "main", "backend" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    # QUAN TRỌNG: Mọi lệnh sẽ chạy trong thư mục backend
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          # Chỉ đường dẫn chính xác tới file lock của backend
          cache-dependency-path: backend/package-lock.json

      - run: npm ci                 # Cài thư viện
      - run: npm run build --if-present # Build (NestJS cần cái này)